#%RAML 1.0 NamedExample

value:
-
   movieid: 1
   moviename: Against the Ice
   location: Mumbai
   showtype: 2D
   language: English
   totalseats : 80
   availableseats : 68
   price: 200
-

  movieid: 2
  moviename: Bird Box
  location:  New Delhi
  showtype: 2D
  language: English
  totalseats : 80
  availableseats : 70
  price: 200

-
   movieid: 3
   moviename: Gold
   location" : Mumbai
   showtype: 2D
   language: Hindi
   totalseats: 80
   availableseats: 50
   price: 200
-

  movieid: 4
  moviename: Spiderman:No way Home
  location: Bengaluru
  showtype: 3D
  language: English
  totalseats : 80,
  availableseats : 20
  price: 200

-

  movieid: 5
  movie_name: 83
  location: New Delhi
  showtype: 2D
  language: Hindi
  totalseats: 80
  availableseats: 40
  price: 200
